INSERT INTO `website_user` (`name`, `username`, `password`, `type`) VALUES
       ('John Doe', 'johndoe@sean.com', 'pass', 'patient'),
       ('Jane Doe', 'janedoe@sean.com', 'pass', 'patient'),
       ('Bob Panckes', 'bobpancakes@sean.com', 'pass', 'patient'),
       ('Betty McBoss', 'bettymcboss@sean.com', 'pass', 'patient'),
       ('Bill Someone', 'billsomeone@sean.com', 'pass', 'patient'),
       ('Whatshisface', 'whatshisface@sean.com', 'pass', 'patient'),
       ('Austin Powers', 'austinpowers@sean.com', 'pass', 'patient'),
       ('Queen Elizabeth II', 'queenelizabeth@sean.com', 'pass', 'patient'),
       ('Judi Dench', 'judidench@sean.com', 'pass', 'patient'),
       ('Mark Twain', 'marktwain@sean.com', 'pass', 'patient'),
       ('Johnny Shen','johnnyshen@sean.com', 'pass', 'doctor'),
       ('Igor Borisov', 'igorborisov@sean.com', 'pass', 'doctor'),
       ('Carolynn Brown', 'carolynnbrown@sean.com', 'pass', 'doctor'),
       ('Nazia Javed', 'naziajaved@sean.com', 'pass', 'doctor'),
       ('Daniel Witten', 'danielwitten@sean.com', 'pass', 'doctor'),
       ('Theodore Buttrick', 'theodorebuttrick@sean.com', 'pass', 'doctor'),
       ('Danielle Hawkins', 'daniellehawkins@sean.com', 'pass', 'doctor'),
       ('Samantha Ghiselli', 'samanthaghiselli@sean.com', 'pass', 'doctor'),
       ('Carrie Hill', 'carriehill@sean.com', 'pass', 'doctor'),
       ('Nancy Krywonis', 'nancykrywonis@sean.com', 'pass', 'doctor'),
       ('Marti Freidnash', 'martifreidnash@sean.com', 'pass', 'doctor'),
       ('Robert Packer', 'robertpacker@sean.com', 'pass', 'doctor'),
       ('Harrison Levine', 'harrisonlevine@sean.com', 'pass', 'doctor'),
       ('Beth Ballen', 'bethballen@sean.com', 'pass', 'doctor'),
       ('Robinette Ball', 'robinetteball@sean.com', 'pass', 'doctor'),
       ('Joel Cooperman', 'joelcooperman@sean.com', 'pass', 'doctor'),
       ('Stuart Myers', 'stuartmyers@sean.com', 'pass', 'doctor'),
       ('Michael Hewitt', 'michaelhewitt@sean.com', 'pass', 'doctor'),
       ('Rudy Kovachevich', 'rudykovachevich@sean.com', 'pass', 'doctor'),
       ('Scott Resig', 'scottresig@sean.com', 'pass', 'doctor'),
       ('Mark Failinger', 'markfailinger@sean.com', 'pass', 'doctor'),
       ('Joanne Takara', 'joannetakara@sean.com', 'pass', 'doctor'),
       ('James Burcham', 'jamesburcham@sean.com', 'pass', 'doctor'),
       ('Matthew Kruger', 'matthewkruger@sean.com', 'pass', 'doctor'),
       ('Robert Keyser', 'robertkeyser@sean.com', 'pass', 'doctor'),
       ('Admin 1', 'superadmin1@gmail.com', 'pass', 'admin'),
       ('Admin 2', 'superadmin2@gmail.com', 'pass', 'admin'),
       ('Admin 3', 'superadmin3@gmail.com', 'pass', 'admin'),
       ('Admin 4', 'superadmin4@gmail.com', 'pass', 'admin'),
       ('Admin 5', 'superadmin5@gmail.com', 'pass', 'admin'),
       ('Lena Smith', 'lenasmith@kaiyue.com', 'pass', 'patient'),
       ('Tom Taylor', 'tomtaylor@kaiyue.com', 'pass', 'patient'),
       ('Nicol Green', 'nicolgreen@kaiyue.com', 'pass', 'patient'),
       ('Paul Miller', 'paulmiller@kaiyue.com', 'pass', 'patient'),
       ('Alen Lee', 'alenlee@kaiyue.com', 'pass', 'patient'),
       ('David King', 'davidking@kaiyue.com', 'pass', 'patient'),
       ('Obmar King', 'obmarking@kaiyue.com', 'pass', 'patient'),
       ('Jone Smith', 'jonesmith@kaiyue.com', 'pass', 'patient'),
       ('Lucy White', 'lucywhite@kaiyue.com', 'pass', 'patient'),
       ('Joanna Smith', 'joannasmith@kaiyue.com', 'pass', 'patient'),
       ('Dennis Anello','dennisanello@kaiyue.com', 'pass', 'doctor'),
       ('Larry Angers', 'larryangers@kaiyue.com', 'pass', 'doctor'),
       ('John Angle', 'johnangle@kaiyue.com', 'pass', 'doctor'),
       ('Richard Annear', 'richardannear@kaiyue.com', 'pass', 'doctor'),
       ('Daniel Ano', 'danielano@kaiyue.com', 'pass', 'doctor'),
       ('Robert Ansell', 'robertansell@kaiyue.com', 'pass', 'doctor'),
       ('Betsy Answer', 'betsyanswer@kaiyue.com', 'pass', 'doctor'),
       ('Scott Antin', 'scottantin@kaiyue.com', 'pass', 'doctor'),
       ('James Baheti', 'jamesbaheti@kaiyue.com', 'pass', 'doctor'),
       ('Ellen Bak', 'ellenbak@kaiyue.com', 'pass', 'doctor'),
       ('Robert Barchi', 'robertbarchi@kaiyue.com', 'pass', 'doctor'),
       ('Shirley Bard', 'shirleybard@kaiyue.com', 'pass', 'doctor'),
       ('John Barlow', 'johnbarlow@kaiyue.com', 'pass', 'doctor'),
       ('Carol Barnes', 'carolbarnes@kaiyue.com', 'pass', 'doctor'),
       ('Harry Truman', 'harrytruman@kaiyue.com', 'pass', 'doctor'),
       ('Franklin Delano', 'franklindelano@kaiyue.com', 'pass', 'doctor'),
       ('John Kennedy', 'johnkennedy@kaiyue.com', 'pass', 'doctor'),
       ('Richard Nixon', 'richardnixon@kaiyue.com', 'pass', 'doctor'),
       ('Gerald Ford', 'geraldford@kaiyue.com', 'pass', 'doctor'),
       ('Jimmy Carter', 'jimmycarter@kaiyue.com', 'pass', 'doctor'),
       ('Ronald Reagan', 'ronaldreagan@kaiyue.com', 'pass', 'doctor'),
       ('George Bush', 'georgbush@kaiyue.com', 'pass', 'doctor'),
       ('Paul Garry', 'paulgarry@kaiyue.com', 'pass', 'doctor'),
       ('Mary White', 'marywhite@kaiyue.com', 'pass', 'doctor'),
       ('Dawn Carter', 'dawncarter@kaiyue.com', 'pass', 'doctor'),
       ('Admin 6', 'superadmin6@kaiyue.com', 'pass', 'admin'),
       ('Admin 7', 'superadmin7@kaiyue.com', 'pass', 'admin'),
       ('Admin 8', 'superadmin8@kaiyue.com', 'pass', 'admin'),
       ('Admin 9', 'superadmin9@kaiyue.com', 'pass', 'admin'),
       ('Admin 10', 'superadmin10@kaiyue.com', 'pass', 'admin'),
       ('Jones Black', 'jonesBlack@gmail.com', 'pass', 'doctor'),
       ('Sam Smith', 'samsmith@gmail.com', 'pass', 'doctor'),
       ('Jonah Hill', 'jonahhill@gmail.com', 'pass', 'doctor'),
       ('Alison Finn', 'alisonfinn@gmail.com', 'pass', 'doctor'),
       ('Don Maroni', 'donmaroni@gmail.com', 'pass', 'doctor'),
       ('Amy Winehouse', 'amywinehouse@gmail.com', 'pass', 'doctor'),
       ('Gary Shimmer', 'garyshimmer@gmail.com', 'pass', 'doctor'),
       ('Pinky Dsuza', 'pinkydsuza@gmail.com', 'pass', 'doctor'),
       ('Shirley Gordon', 'shirleygordon@gmail.com', 'pass', 'doctor'),
       ('Hilary Birgham', 'hilarybirgham@gmail.com', 'pass', 'doctor'),
       ('Olivia Redson', 'oliviaredson@gmail.com', 'pass', 'doctor'),
       ('Shin Yuu', 'shinyuu@gmail.com', 'pass', 'doctor'),
       ('Walter Whistle', 'walterwhistle@gmail.com', 'pass', 'doctor'),
       ('Bruce Wayne', 'brucewayne@gmail.com', 'pass', 'doctor'),
       ('Clarke Kent', 'clarkekent@gmail.com', 'pass', 'doctor'),
       ('Cory Anderson', 'coryanderson@gmail.com', 'pass', 'doctor'),
       ('Leo Kaplin', 'leokaplin@gmail.com', 'pass', 'doctor'),
       ('Andy Goshun', 'andygoshun@gmail.com', 'pass', 'doctor'),
       ('Ram Kapoor', 'ramkapoor@gmail.com', 'pass', 'doctor'),
       ('Ali Miyaan', 'alimiyaan@gmail.com', 'pass', 'doctor'),
       ('Shin Chan', 'shinchan@gmail.com', 'pass', 'doctor'),
       ('Jack Humpty', 'jackhumpty@gmail.com', 'pass', 'doctor'),
       ('Green Goblin', 'greengoblin@gmail.com', 'pass', 'doctor'),
       ('Goldy Fish', 'goldyfish@gmail.com', 'pass', 'doctor'),
       ('Anna Harbor', 'annaharbor@gmail.com', 'pass', 'doctor'),
	('Sara John', 'Sara_George@gmail.com', '123ssf', 'doctor'),
       ('George Jane', 'George@outlook.com', '4546gdg', 'doctor'),
       ('Robert Bob', 'Robert@gmail.com', '6gdhd78', 'doctor'),
       ('Brent Betty', 'Brent@gmail.com', '6875hff', 'doctor'),
       ('Jaster Bill', 'Jaster23@gmail.com', '353fft', 'doctor'),
       ('Daniel Austin', 'Daniel@gmail.com', '7974mg', 'doctor'),
       ('Aaron George', 'Aaron@outlook.com', '2226gdg', 'doctor'),
       ('Hoover Robert', 'Hoover@gmail.com', '33hd78', 'doctor'),
       ('Erin Brent', 'Erin@gmail.com', '4575hff', 'doctor'),
       ('Welch Jaster', 'Welch23@gmail.com', '7753fft', 'doctor'),
       ('Andrew Daniel', 'Andrew@gmail.com', 'ds454mg', 'doctor'),
       ('Javed Liz', 'Javed@gmail.com', '9874nmk', 'doctor'),
       ('Morgan Judi', 'Morgan@yahoo.com', '324fedg', 'doctor'),
       ('Rebecca Mark', 'Rebecca@gmail.com', 'wer543', 'doctor'),
       ('Witten Johnny','Witten@outlook.com', '987hhjj', 'doctor'),
       ('Nazia Anderson', 'Nazia@gmail.com', '324fdgs', 'doctor'),
       ('Ahmad Saleh', 'Ahmad@yahoo.com', '555trtf', 'doctor'),
       ('Scott Daniel', 'Scott@gmail.com', '3256gfd', 'doctor'),
       ('Amera Omar', 'Amera@yahoo.com', '24fdfv', 'patient'),
       ('Michael Danielle', 'Michael@gmail.com', 'kjk786', 'patient'),
       ('Yasser Sameer', 'Yasser@yahoo.com', '352cgdg', 'patient'),
       ('Yasmin Jamal', 'Yasmin@outlook.com', '54gdf4', 'patient'),
       ('Turkey Ahmad', 'Turkey@gmail.com', 'hgjft65', 'patient'),
       ('Awatif Sultan', 'Awatif@gmail.com', '342ghf', 'doctor'),
       ('Khalid Bander', 'Khalid@outlook.com', '8jt765d', 'doctor'),
       ('Shatha Omair', 'Shatha@gmail.com', '422fgs', 'doctor'),
       ('Jood Abdul', 'Jood34@gmail.com', 'fgew435', 'doctor'),
       ('Ali Bader', 'Ali123@yahoo.com', 'vfsdf3', 'doctor'),
       ('Jamila Hasan', 'Jamila22@gmail.com', '424fsg5', 'doctor'),
       ('Ayman Nayf', 'Ayman15@gmail.com.com', '5365hd', 'doctor'),
       ('Abdulla Tareq', 'Abdulla23@yahoo.com', 'cft432', 'admin');

INSERT INTO `website_doctor` (`phoneNumber`, `officeHours`, `speciality`, `rating`, `availability`, `state`, `city`, `zip`, `street`, `education`, `awards`, `experience`, `username_id`) VALUES
       ('3036928000', 'Mon-Fri: 8 - 5', 'Primary Care', 5, '', 'Colorado', 'Denver', '80246', '760 South Colorado Blvd.', 'University of Texas, San Antonio', '', 'Dr. Shen is a board-certified physician with a specialty in family medicine', 'johnnyshen@sean.com'),
       ('', 'Mon-Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80220', '4500 East 9th Avenue', 'Vilnius Univeristy of Medicine', '', 'Good Samaritan Hospital Residence in Internal Medicine', 'igorborisov@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80220', '50 South Steele Street', 'University of Colorado', '', 'Rose Medical Center Residency in Family Medicine', 'carolynnbrown@sean.com'),
       ('', 'Mon - Fri: 8 -5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80239', '10515 East 40th Ave.', 'King Edward Medical University', '', 'Pheonix Baptist Hospital, Residency in Family Medicine', 'naziajaved@sean.com'),
       ('', 'Mon - Fri: 8-5', 'Primary Care', 5, '', 'Colorado', 'Denver', '80220', '4500 East 9th Avenue', 'Vilnius University of Medicine', '', 'University of Colorado Residency in Internal Medicine', 'danielwitten@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Primary Care', 5, '', 'Colorado', 'Wheatridge', '80033', '4045 Wadsworth Blvd.', 'Wayne State Univeristy', '', 'Saint Luke Medical Center Residency', 'theodorebuttrick@sean.com'),
       ('', 'Mon-Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80207', '2970 Quebec Street', 'Michigan State University', '', 'University of New Mexico, Residency in Dermatology', 'daniellehawkins@sean.com'),
       ('', 'Mon-Fri: 8 - 5', 'Dermatologist', 4.5, '', 'Colorado', 'Denver', '80207', '2970 Quebec Street', 'University of California Irvine', '', 'University of California Irvine, residency in Dermatology', 'samanthaghiselli@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Dermatologist', 4.5, '', 'Colroado', 'Denver', '80206', '3300 East 1st Ave', 'University of Colorado', '', 'University of Iowa, Residency in Dermatology', 'carriehill@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80220', '4545 E 9th Ave', 'University of Manitoba Faculty of Medicine', '', 'University of Minnesota, Residency in Dermatology', 'nancykrywonis@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80230', '130 Rampart Way', 'University of Colorado', '', 'University of Colorado Hospital, Residency in Dermatology', 'martifreidnash@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Wheatridge', '80033', '8550 W. 38th Avenue', 'University of Tennesse', '', 'Vanderbilt University Medical Center, Residency in Dermatology', 'robertpacker@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80206', '3570 E 12th Ave', 'Columbia University, Medical School for International Health', '', 'University of Michigan, Residency', 'harrisonlevine@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Centennial', '80111', '6081 S Quebec St', 'Eastern Virginia Medical School', '', 'University of Colorado, Residency in General Psychiatry', 'bethballen@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80246', '4550 E Cherry Creek South Drive', 'Columbia University', '', 'Bronx University, Internship', 'robinetteball@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80014', '10555 E Dartmouth Ave', 'A.T. Stills University, Kirksville', '', 'rand View Hospital, Residency in Orthopedic Surgery', 'joelcooperman@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1411 South Potomac Street', 'University of Pennsylvania', '', 'ohn Hopkins University, Residency in Orthopedic Surgery', 'stuartmyers@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1411 South Potomac Street', 'Tufts University', '', 'Harbor-University California Los Angeles, Residency', 'michaelhewitt@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1300 South Potomac Street', 'University of Illinois, Chicago', '', 'Mayo Clinic, Residency in Orthopedic Surgery', 'rudykovachevich@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '8101 E. Lowry Blvd', 'University of Minnesota', '', 'University of Minnesota, Residency in Orthopedic Surgery', 'scottresig@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '8101 E Lowry Blvd', 'University of Minnesota, Twin Cities', '', 'University of Texas, Residency in Orthopedic Surgery', 'markfailinger@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Aurora', '80011', '750 Potomac Street', 'Indiana University', '', 'Tucson Veterans Affairs Medical Center, Residency', 'joannetakara@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Aurora', '80011', '750 Potomac Street', 'University of Missouri, Columbia', '', 'University of Colorado, Residency in Opthalmology', 'jamesburcham@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Denver', '80246', '4999 E Kentucky Ave', 'Tufts University', '', 'University of Texas, Southwestern, Residency in Opthalmology', 'matthewkruger@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Eye Doctor', 4.5, '', 'Colorado', 'Lakewood', '80228', '11750 W 2nd Place', 'University of Michigan', '', 'University of Colorado, Residency in Opthalmology', 'robertkeyser@sean.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Primary Care', 5, '', 'Colorado', 'Denver', '80246', '760 South Colorado Blvd.', 'University of Texas, San Antonio', '', 'Dr. Shen is a board-certified physician with a specialty in family medicine', 'dennisanello@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80220', '4500 East 9th Avenue', 'Vilnius Univeristy of Medicine', '', 'Good Samaritan Hospital Residence in Internal Medicine', 'larryangers@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80220', '50 South Steele Street', 'University of Colorado', '', 'Rose Medical Center Residency in Family Medicine', 'johnangle@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80239', '10515 East 40th Ave.', 'King Edward Medical University', '', 'Pheonix Baptist Hospital, Residency in Family Medicine', 'richardannear@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80220', '4500 East 9th Avenue', 'Vilnius University of Medicine', '', 'University of Colorado Residency in Internal Medicine', 'danielano@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Wheatridge', '80033', '4045 Wadsworth Blvd.', 'Wayne State Univeristy', '', 'Saint Luke Medical Center Residency', 'robertansell@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80207', '2970 Quebec Street', 'Michigan State University', '', 'University of New Mexico, Residency in Dermatology', 'betsyanswer@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 4.5, '', 'Colorado', 'Denver', '80207', '2970 Quebec Street', 'University of California Irvine', '', 'University of California Irvine, residency in Dermatology', 'scottantin@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Dermatologist', 4.5, '', 'Colroado', 'Denver', '80206', '3300 East 1st Ave', 'University of Colorado', '', 'University of Iowa, Residency in Dermatology', 'jamesbaheti@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80220', '4545 E 9th Ave', 'University of Manitoba Faculty of Medicine', '', 'University of Minnesota, Residency in Dermatology', 'ellenbak@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80230', '130 Rampart Way', 'University of Colorado', '', 'University of Colorado Hospital, Residency in Dermatology', 'robertbarchi@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Wheatridge', '80033', '8550 W. 38th Avenue', 'University of Tennesse', '', 'Vanderbilt University Medical Center, Residency in Dermatology', 'shirleybard@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80206', '3570 E 12th Ave', 'Columbia University, Medical School for International Health', '', 'University of Michigan, Residency', 'johnbarlow@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Centennial', '80111', '6081 S Quebec St', 'Eastern Virginia Medical School', '', 'University of Colorado, Residency in General Psychiatry', 'carolbarnes@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80246', '4550 E Cherry Creek South Drive', 'Columbia University', '', 'Bronx University, Internship', 'harrytruman@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80014', '10555 E Dartmouth Ave', 'A.T. Stills University, Kirksville', '', 'rand View Hospital, Residency in Orthopedic Surgery', 'franklindelano@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1411 South Potomac Street', 'University of Pennsylvania', '', 'ohn Hopkins University, Residency in Orthopedic Surgery', 'johnkennedy@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1411 South Potomac Street', 'Tufts University', '', 'Harbor-University California Los Angeles, Residency', 'richardnixon@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1300 South Potomac Street', 'University of Illinois, Chicago', '', 'Mayo Clinic, Residency in Orthopedic Surgery', 'geraldford@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '8101 E. Lowry Blvd', 'University of Minnesota', '', 'University of Minnesota, Residency in Orthopedic Surgery', 'jimmycarter@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '8101 E Lowry Blvd', 'University of Minnesota, Twin Cities', '', 'University of Texas, Residency in Orthopedic Surgery', 'ronaldreagan@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Aurora', '80011', '750 Potomac Street', 'Indiana University', '', 'Tucson Veterans Affairs Medical Center, Residency', 'georgbush@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Aurora', '80011', '750 Potomac Street', 'University of Missouri, Columbia', '', 'University of Colorado, Residency in Opthalmology', 'paulgarry@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Denver', '80246', '4999 E Kentucky Ave', 'Tufts University', '', 'University of Texas, Southwestern, Residency in Opthalmology', 'marywhite@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Eye Doctor', 4.5, '', 'Colorado', 'Lakewood', '80228', '11750 W 2nd Place', 'University of Michigan', '', 'University of Colorado, Residency in Opthalmology', 'dawncarter@kaiyue.com'),
       ('9889789876', 'Mon-Fri 10am-2pm', 'ENT', 4.5, '','Arizona', 'Glendale', '85301', '', 'MD', 'Gold Award', '15 years', 'jonesblack@gmail.com' ),
	('9889789813', 'Mon-Tue 8am-11am', 'Primary Care', 3.5, '','California', 'Albany', '94706','', 'MD', 'Silver Award', '5 years', 'samsmith@gmail.com' ),
	('9889789853', 'Thr-Fri 10am-2pm', 'Dentist', 4.0, '','Ohio', 'Greenfield', '45123','', 'MBBS', 'Gold Award', '5 years', 'jonahhill@gmail.com' ),
	('9889789864', 'Mon-Fri 3pm-7pm', 'Dermatologist', 4.0, '','New York', 'Auburn', '13021','', 'MD', 'Gold Award', '5 years', 'alisonfinn@gmail.com' ),
	('9889789875', 'Sat-Sun 6pm-8pm', 'Eye Doctor', 4.8, '','Washington', 'Colville', '99114','', 'MD', 'Gold Award', '10 years', 'donmaroni@gmail.com' ),
	('9889789872', 'Mon-Fri 10am-2pm', 'Psychiatrist', 4.2, '','Colorado', 'Boulder', '80301','', 'MD', 'Platinum Award', '25 years', 'amywinehouse@gmail.com' ),
	('9889789827', 'Tue, Thr 1pm-5pm', 'Orthopedist', 4.4, '','California', 'Berkeley', '94704','', 'MD', 'Gold Award', '5 years', 'garyshimmer@gmail.com' ),
	('9889789858', 'Wed-Fri 5pm-8pm', 'Dentist', 4.9, '','Colorado', 'Boulder', '80307','', 'MD', 'Gold Award', '13 years', 'pinkydsuza@gmail.com' ),
	('9889789826', 'Mon-Wed 4pm-6pm', 'ENT', 3.8, '','Delaware', 'Bear', '19701','', 'DM', 'Gold Award', '5 years', 'shirleygordon@gmail.com' ),
	('9889789847', 'Mon-Thr 3pm-5pm', 'Primary Care', 4.8, '','Florida', 'High Springs', '32643','', 'MD', 'Gold Award', '5 years', 'hilarybirgham@gmail.com' ),
	('9889789873', 'Tue-Fri 6pm-9pm', 'Psychiatrist', 2.8, '','Oregon', 'Canby', '97013','','MD', 'Gold Award', '9 years', 'oliviaredson@gmail.com' ),
	('9889789883', 'Fri 10am-2pm', 'Orthopedist', 3.6, '','Nevada', 'Las Vegas', '89044','','MD', 'Gold Award', '5 years', 'shinyuu@gmail.com' ),
	('9889789858', 'Mon-Tues 4pm-6pm', 'Dermatologist', 4.6, '','Utah', 'Logan', '84321','','MD', 'Gold Award', '5 years', 'walterwhistle@gmail.com' ),
	('9889789817', 'Fri-Sat 10am-5pm', 'Primary Care', 3.9, '','Wisconsin', 'Racine', '53126','','MBBS', 'Gold Award', '2 years', 'brucewayne@gmail.com' ),
	('9889789859', 'Mon-Wed 10am-2pm', 'Eye Doctor', 4.2, '','Colorado', 'Boulder', '80328','','MD', 'Gold Award', '5 years', 'clarkekent@gmail.com' ),
	('9889789837', 'Sun-Mon 3pm-5pm', 'Psychiatrist', 4.8, '','Kansas', 'Holton', '66436','','MD', 'Gold Award', '5 years', 'coryanderson@gmail.com' ),
	('9889789837', 'Wed-Thr 9am-12pm', 'Dermatologist', 4.3, '','California', 'Irvine', '92606','','MBBS', 'Gold Award', '7 years', 'leokaplin@gmail.com' ),
	('9889789848', 'Wed-Fri 7pm-9pm', 'Primary Care', 4.1, '','Arizona', 'Benson', '85602','','MD', 'Gold Award', '5 years', 'andygoshun@gmail.com' ),
	('9889789858', 'Mon-Fri 2pm-5pm', 'ENT', 3.1, '','Iowa', 'Forest City', '50436','','MD', 'Gold Award', '5 years', 'ramkapoor@gmail.com' ),
	('98897898569', 'Mon-Fri 10am-5pm', 'Orthopedist', 4.5, '','Colorado', 'Broomfield', '80021','','MD', 'Gold Award', '5 years', 'alimiyaan@gmail.com' ),
	('9889789859', 'Tue-Thr 12pm-2pm', 'ENT', 4.9, '','Kansas', 'Colby', '67701','','MD', 'Gold Award', '5 years', 'shinchan@gmail.com' ),
	('9889789837', 'Mon-Tue 11am-1pm', 'Eye Doctor', 4.7, '','California', 'Riverside', '92505','','MD', 'Gold Award', '5 years', 'jackhumpty@gmail.com' ),
	('9889789858', 'Mon-Fri 4pm-6pm', 'Dentist', 4.0, '','Arizona', 'Bisbee', '85603','','DM', 'Gold Award', '25 years', 'greengoblin@gmail.com' ),
  	('9889789869', 'Fri-Sun 6pm-9pm', 'Primary Care', 5.0,'','Iowa', 'Iowa City', '52241','','MD', 'Gold Award', '15 years', 'goldyfish@gmail.com' ),
	('9889789896', 'Mon-Wed 4pm-7pm', 'Orthopedist', '','Colorado', 'Broomfield', '80038','','MD', 'Gold Award', '15 years', 'annaharbor@gmail.com' ),
	('3037770400', 'Mon - Thur: 8 - 5', 'ENT', 4, '', 'Colorado', 'Boulder', '80301', '', 'University of Texas, San Antonio', '', '', 'Sara_George@gmail.com'),
       ('3035770050', 'Tue - Fri: 8 - 5', 'ENT', 3.5, '', 'Colorado', 'Denver', '80220', '', 'Vilnius Univeristy of Medicine', '', '', 'George@outlook.com'),
       ('3034770006', 'Mon - Fri: 8 - 6', 'Primary Care', 4.5, '', 'Colorado', 'Boulder', '80306', '', 'University of Colorado', '', '', 'Robert@gmail.com'),
       ('3037370002', 'Mon - Fri: 8 -5', 'Primary Care', 4.2, '', 'Colorado', 'Denver', '80239', '', 'King Edward Medical University', '', '', 'Brent@gmail.com'),
       ('3032770005', 'Tue - Fri: 9 - 5', 'Primary Care', 5, '', 'Colorado', 'Boulder', '80310', '', 'Vilnius University of Medicine', '', '', 'Jaster23@gmail.com'),
       ('3031770003', 'Mon - Fri: 9 - 5', 'Primary Care', 5, '', 'Colorado', 'Golden', '80402', '', 'Wayne State Univeristy', '', '', 'Daniel@gmail.com'),
       ('3037670040', 'Mon-Fri: 8 - 5', 'Dermatologist', 4.9, '', 'Colorado', 'Denver', '80207', '', 'Michigan State University', '', '', 'Aaron@outlook.com'),
       ('3037870600', 'Mon-Fri: 8 - 6', 'Dermatologist', 4.5, '', 'Colorado', 'Denver', '80207', '', 'University of California Irvine', '', '', 'Hoover@gmail.com'),
       ('3037970070', 'Mon - Fri: 8 - 5', 'Dermatologist', 4.5, '', 'Colroado', 'Louisville', '80027', '', 'University of Colorado', '', '', 'Erin@gmail.com'),
       ('3035770003', 'Mon - Fri: 8 - 6', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80220', '', 'University of Manitoba Faculty of Medicine', '', '', 'Welch23@gmail.com'),
       ('3037670005', 'Mon - Fri: 10 - 8', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80230', '', 'University of Colorado', '', '', 'Andrew@gmail.com'),
       ('3037170070', 'Mon - Fri: 8 - 5', 'Dermatologist', 3.7, '', 'Colorado', 'Golden', '80402', '', 'University of Tennesse', '', '', 'Javed@gmail.com'),
       ('3032770333', 'Mon - Fri: 8 - 6', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80206', '', 'Columbia University, Medical School for International Health', '', '', 'Morgan@yahoo.com'),
       ('3033770444', 'Mon - Fri: 8 - 5', 'Psychiatrist', 3.9, '', 'Colorado', 'Centennial', '80111', '', 'Eastern Virginia Medical School', '', '', 'Rebecca@gmail.com'),
       ('3034770567', 'Mon - Fri: 8 - 4', 'Psychiatrist', 3.5, '', 'Colorado', 'Denver', '80246', '', 'Columbia University', '', '', 'Witten@outlook.com'),
       ('3035770440', 'Tue - Fri: 9 - 5', 'Orthopedist', 5, '', 'Colorado', 'Broomfield', '80020', '', 'A.T. Stills University, Kirksville', '', '', 'Nazia@gmail.com'),
       ('3036770076', 'Mon - Fri: 8 - 4', 'Orthopedist', 4.8, '', 'Colorado', 'Louisville', '80027', '', 'University of Pennsylvania', '', '', 'Ahmad@yahoo.com'),
       ('3037770340', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '', 'Tufts University', '', '', 'Scott@gmail.com'),
       ('3038770089', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Broomfield', '80020', '', 'University of Illinois, Chicago', '', '', 'Awatif@gmail.com'),
       ('3039770222', 'Mon - Fri: 8 - 6', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '', 'University of Minnesota', '', '', 'Khalid@outlook.com'),
       ('3034770034', 'Mon - Fri: 8 - 5', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '', 'University of Minnesota, Twin Cities', '', '', 'Shatha@gmail.com'),
       ('3039770087', 'Mon - Fri: 8 - 4', 'Eye Doctor', 5, '', 'Colorado', 'Louisville', '80027', '', 'Indiana University', '', '', 'Jood34@gmail.com'),
       ('3037070230', 'Tue - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Aurora', '80011', '', 'University of Missouri, Columbia', '', '', 'Ali123@yahoo.com'),
       ('3031770011', 'Mon - Thur: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Denver', '80246', '', 'Tufts University', '', '', 'Jamila22@gmail.com'),
       ('3037770035', 'Mon - Fri: 9 - 5', 'Eye Doctor', 4.7, '', 'Colorado', 'Lakewood', '80228', '', 'University of Michigan', '', '', 'Ayman15@gmail.com');

INSERT INTO `website_favoritedoctors` (`patient_id`, `doctor_id`) VALUES
       ('marktwain@sean.com', 'johnnyshen@sean.com'),
       ('marktwain@sean.com', 'michaelhewitt@sean.com'),
       ('bobpancakes@sean.com', 'igorborisov@sean.com'),
       ('bettymcboss@sean.com', 'rudykovachevich@sean.com'),
       ('bettymcboss@sean.com', 'joannetakara@sean.com'),
       ('bettymcboss@sean.com', 'stuartmyers@sean.com'),
       ('bettymcboss@sean.com', 'theodorebuttrick@sean.com'),
       ('bettymcboss@sean.com', 'bethballen@sean.com'),
       ('bettymcboss@sean.com', 'danielwitten@sean.com'),
       ('bettymcboss@sean.com', 'carriehill@sean.com'),
       ('bettymcboss@sean.com', 'robertkeyser@sean.com'),
       ('billsomeone@sean.com', 'robertkeyser@sean.com'),
       ('billsomeone@sean.com', 'theodorebuttrick@sean.com'),
       ('johndoe@sean.com', 'bethballen@sean.com'),
       ('johndoe@sean.com', 'theodorebuttrick@sean.com'),
       ('johndoe@sean.com', 'markfailinger@sean.com'),
       ('johndoe@sean.com', 'harrisonlevine@sean.com'),
       ('johndoe@sean.com', 'jamesburcham@sean.com'),
       ('judidench@sean.com', 'johnnyshen@sean.com'),
       ('judidench@sean.com', 'theodorebuttrick@sean.com'),
       ('judidench@sean.com', 'igorborisov@sean.com'),
       ('judidench@sean.com', 'nancykrywonis@sean.com'),
       ('janedoe@sean.com', 'naziajaved@sean.com'),
       ('janedoe@sean.com', 'joelcooperman@sean.com'),
       ('janedoe@sean.com', 'igorborisov@sean.com'),
       ('lenasmith@kaiyue.com', 'dennisanello@kaiyue.com'),
       ('lenasmith@kaiyue.com', 'larryangers@kaiyue.com'),   
       ('tomtaylor@kaiyue.com', 'johnangle@kaiyue.com'),
       ('tomtaylor@kaiyue.com', 'richardannear@kaiyue.com'),
       ('tomtaylor@kaiyue.com', 'danielano@kaiyue.com'),   
       ('nicolgreen@kaiyue.com', 'robertansell@kaiyue.com'),
       ('nicolgreen@kaiyue.com', 'betsyanswer@kaiyue.com'),    
       ('paulmiller@kaiyue.com', 'scottantin@kaiyue.com'),
       ('paulmiller@kaiyue.com', 'jamesbaheti@kaiyue.com'),
       ('paulmiller@kaiyue.com', 'ellenbak@kaiyue.com'),
       ('alenlee@kaiyue.com', 'robertbarchi@kaiyue.com'),
       ('alenlee@kaiyue.com', 'shirleybard@kaiyue.com'),
       ('davidking@kaiyue.com', 'johnbarlow@kaiyue.com'),
       ('davidking@kaiyue.com', 'carolbarnes@kaiyue.com'),
       ('davidking@kaiyue.com', 'harrytruman@kaiyue.com'),   
       ('obmarking@kaiyue.com', 'franklindelano@kaiyue.com'),
       ('obmarking@kaiyue.com', 'johnkennedy@kaiyue.com'),   
       ('jonesmith@kaiyue.com', 'richardnixon@kaiyue.com'),
       ('jonesmith@kaiyue.com', 'geraldford@kaiyue.com'),
       ('jonesmith@kaiyue.com', 'jimmycarter@kaiyue.com'),
       ('lucywhite@kaiyue.com', 'ronaldreagan@kaiyue.com'),
       ('lucywhite@kaiyue.com', 'georgbush@kaiyue.com'),
       ('joannasmith@kaiyue.com', 'paulgarry@kaiyue.com'),
       ('joannasmith@kaiyue.com', 'marywhite@kaiyue.com'),
       ('joannasmith@kaiyue.com', 'dawncarter@kaiyue.com'),
       ('bobpancakes@sean.com', 'jonahhill@gmail.com'),
       ('marktwain@sean.com', 'amywinehouse@gmail.com'),
       ('bobpancakes@sean.com', 'coryanderson@gmail.com'),
       ('marktwain@sean.com', 'shinchan@gmail.com'),
       ('bobpancakes@sean.com', 'shirleygordon@gmail.com'),
       ('marktwain@sean.com', 'goldyfish@gmail.com'),
       ('bobpancakes@sean.com', 'greengoblin@gmail.com'),
       ('marktwain@sean.com', 'garyshimmer@gmail.com'),
       ('bobpancakes@sean.com', 'leokaplin@gmail.com'),
       ('marktwain@sean.com', 'jonesBlack@gmail.com'),
       ('whatshisface@sean.com', 'jonahhill@gmail.com'),
       ('austinpowers@sean.com', 'amywinehouse@gmail.com'),
       ('whatshisface@sean.com', 'clarkekent@gmail.com'),
       ('austinpowers@sean.com', 'coryanderson@gmail.com'),
       ('whatshisface@sean.com', 'leokaplin@gmail.com'),
       ('austinpowers@sean.com', 'andygoshun@gmail.com'),
       ('whatshisface@sean.com', 'alimiyaan@gmail.com'),
       ('austinpowers@sean.com', 'shinchan@gmail.com'),
       ('whatshisface@sean.com', 'jackhumpty@gmail.com'),
       ('austinpowers@sean.com', 'annaharbor@gmail.com'),
       ('queenelizabeth@sean.com', 'leokaplin@gmail.com'),
       ('bettymcboss@sean.com', 'andygoshun@gmail.com'),
       ('bettymcboss@sean.com', 'alimiyaan@gmail.com'),
       ('bettymcboss@sean.com', 'shinchan@gmail.com'),
       ('bettymcboss@sean.com', 'jackhumpty@gmail.com'),
       ('Amera@yahoo.com', 'Ayman15@gmail.com'),
       ('Amera@yahoo.com', 'Jood34@gmail.com'),
       ('Amera@yahoo.com', 'Rebecca@gmail.com'),
       ('Amera@yahoo.com', 'Aaron@outlook.com'),
       ('Amera@yahoo.com', 'George@outlook.com'),
       ('Michael@gmail.com', 'Hoover@gmail.com'),
       ('Michael@gmail.com', 'Sara_George@gmail.com'),
       ('Michael@gmail.com', 'Ayman15@gmail.com'),
       ('Michael@gmail.com', 'Aaron@outlook.com'),
       ('Michael@gmail.com', 'George@outlook.com'),
       ('Yasser@yahoo.com', 'Sara_George@gmail.com'),
       ('Yasser@yahoo.com', 'Rebecca@gmail.com'),
       ('Yasser@yahoo.com', 'Javed@gmail.com'),
       ('Yasmin@outlook.com', 'Javed@gmail.com'),
       ('Yasser@yahoo.com', 'Welch23@gmail.com'),
       ('Yasser@yahoo.com', 'Scott@gmail.com'),
       ('Yasmin@outlook.com', 'Robert@gmail.com'),
       ('Yasmin@outlook.com', 'Scott@gmail.com'),
       ('Yasmin@outlook.com', 'Brent@gmail.com'),
       ('Turkey@gmail.com', 'Robert@gmail.com'),
       ('Yasmin@outlook.com', 'Ayman15@gmail.com'),
       ('Turkey@gmail.com', 'Rebecca@gmail.com'),
       ('Turkey@gmail.com', 'Brent@gmail.com'),
       ('Turkey@gmail.com', 'Jood34@gmail.com'),
       ('Turkey@gmail.com', 'Morgan@yahoo.com');


INSERT INTO `website_insurance` (`name`, `doctor_id`) VALUES
       ('Aetna', 'johnnyshen@sean.com'),
       ('Cigna', 'johnnyshen@sean.com'),
       ('Medicare', 'johnnyshen@sean.com'),
       ('United', 'johnnyshen@sean.com'),
       ('Aetna', 'igorborisov@sean.com'),
       ('Blue', 'igorborisov@sean.com'),
       ('Cigna', 'igorborisov@sean.com'),
       ('United', 'igorborisov@sean.com'),
       ('Aetna', 'carolynnbrown@sean.com'),
       ('Blue', 'carolynnbrown@sean.com'),
       ('Cigna', 'carolynnbrown@sean.com'),
       ('United', 'carolynnbrown@sean.com'),
       ('Aetna', 'naziajaved@sean.com'),
       ('Blue', 'naziajaved@sean.com'),
       ('Cigna', 'naziajaved@sean.com'),
       ('United', 'naziajaved@sean.com'),
       ('Aetna', 'danielwitten@sean.com'),
       ('Blue', 'danielwitten@sean.com'),
       ('Cigna', 'danielwitten@sean.com'),
       ('United', 'danielwitten@sean.com'),
       ('Aetna', 'theodorebuttrick@sean.com'),
       ('Blue', 'theodorebuttrick@sean.com'),
       ('Cigna', 'theodorebuttrick@sean.com'),
       ('Medicare', 'theodorebuttrick@sean.com'),
       ('United', 'theodorebuttrick@sean.com'),
       ('Aetna', 'dennisanello@kaiyue.com'),
       ('Cigna', 'dennisanello@kaiyue.com'),
       ('Medicare', 'dennisanello@kaiyue.com'),
       ('United', 'dennisanello@kaiyue.com'),
       ('Aetna', 'larryangers@kaiyue.com'),
       ('Blue', 'larryangers@kaiyue.com'),
       ('Cigna', 'larryangers@kaiyue.com'),
       ('United', 'larryangers@kaiyue.com'),
       ('Aetna', 'johnangle@kaiyue.com'),
       ('Blue', 'johnangle@kaiyue.com'),
       ('Cigna', 'johnangle@kaiyue.com'),
       ('United', 'johnangle@kaiyue.com'),
       ('Aetna', 'richardannear@kaiyue.com'),
       ('Blue', 'richardannear@kaiyue.com'),
       ('Cigna', 'richardannear@kaiyue.com'),
       ('United', 'richardannear@kaiyue.com'),
       ('Aetna', 'danielano@kaiyue.com'),
       ('Blue', 'danielano@kaiyue.com'),
       ('Cigna', 'danielano@kaiyue.com'),
       ('United', 'danielano@kaiyue.com'),
       ('Aetna', 'robertansell@kaiyue.com'),
       ('Blue', 'robertansell@kaiyue.com'),
       ('Cigna', 'robertansell@kaiyue.com'),
       ('Medicare', 'robertansell@kaiyue.com'),
       ('United', 'robertansell@kaiyue.com'),
       ('Aetna', 'jonahhill@gmail.com'),
       ('Cigna', 'amywinehouse@gmail.com'),
       ('Medicare', 'jonahhill@gmail.com'),
       ('United', 'jonahhill@gmail.com'),
       ('Aetna', 'amywinehouse@gmail.com'),
       ('Blue', 'amywinehouse@gmail.com'),
       ('Cigna', 'clarkekent@gmail.com'),
       ('United', 'clarkekent@gmail.com'),
       ('Aetna', 'clarkekent@gmail.com'),
       ('Blue', 'clarkekent@gmail.com'),
       ('Cigna', 'annaharbor@gmail.com'),
       ('United', 'annaharbor@gmail.com'),
       ('Aetna', 'annaharbor@gmail.com'),
       ('Blue', 'shinchan@gmail.com'),
       ('Cigna', 'shinchan@gmail.com'),
       ('United', 'shinchan@gmail.com'),
       ('Aetna', 'shinchan@gmail.com'),
       ('Blue', 'leokaplin@gmail.com'),
       ('Cigna', 'leokaplin@gmail.com'),
       ('United', 'leokaplin@gmail.com'),
       ('Aetna', 'jackhumpty@gmail.com'),
       ('Blue', 'jackhumpty@gmail.com'),
       ('Cigna', 'theodorebuttrick@sean.com'),
       ('Medicare', 'theodorebuttrick@sean.com'),
       ('United', 'theodorebuttrick@sean.com'),
       ('Aetna', 'Rebecca@gmail.com'),
       ('Cigna', 'Rebecca@gmail.com'),
       ('Medicare', 'Rebecca@gmail.com'),
       ('United', 'Rebecca@gmail.com'),
       ('Aetna', 'Sara_George@gmail.com'),
       ('Blue', 'Sara_George@gmail.com'),
       ('Cigna', 'Sara_George@gmail.com'),
       ('United', 'Sara_George@gmail.com'),
       ('Aetna', 'Aaron@outlook.com'),
       ('Blue', 'Aaron@outlook.com'),
       ('Cigna', 'Aaron@outlook.com'),
       ('United', 'Aaron@outlook.com'),
       ('Aetna', 'Javed@gmail.com'),
       ('Blue', 'Javed@gmail.com'),
       ('Cigna', 'Javed@gmail.com'),
       ('United', 'Javed@gmail.com'),
       ('Aetna', 'Ayman15@gmail.com'),
       ('Blue', 'Ayman15@gmail.com'),
       ('Cigna', 'Ayman15@gmail.com'),
       ('United', 'Ayman15@gmail.com'),
       ('Aetna', 'Robert@gmail.com'),
       ('Blue', 'Robert@gmail.com'),
       ('Cigna', 'Robert@gmail.com'),
       ('Medicare', 'Robert@gmail.com'),
       ('United', 'Robert@gmail.com');

INSERT INTO `website_review` (`rating`, `comment`, `doctor_id`, `patient_id`, `date`) VALUES
       (4, 'Good job', 'johnnyshen@sean.com', 'johndoe@sean.com', ''),
       (4, 'Good job', 'theodorebuttrick@sean.com', 'johndoe@sean.com', ''),
       (4, 'Good job', 'igorborisov@sean.com', 'johndoe@sean.com', ''),
       (4, 'Good job', 'markfailinger@sean.com','johndoe@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'bobpancakes@sean.com', ''),
       (4, 'Good job', 'carriehill@sean.com', 'judidench@sean.com', ''),
       (4, 'Good job', 'theodorebuttrick@sean.com', 'judidench@sean.com', ''),
       (4, 'Good job', 'matthewkruger@sean.com', 'judidench@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'theodorebuttrick@sean.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'danielwitten@sean.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'joannetakara@sean.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'marktwain@sean.com', ''),
       (4, 'Good job', 'robertkeyser@sean.com', 'marktwain@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'billsomeone@sean.com', ''),
       (4, 'Good job', 'naziajaved@sean.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'robertkeyser@sean.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'rudykovachevich@sean.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'harrisonlevine@sean.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'bethballen@sean.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'carolynnbrown@sean.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'stuartmyers@sean.com', 'austinpowers@sean.com', ''),
       (4, 'Good job', 'robinetteball@sean.com', 'austinpowers@sean.com', ''),
       (4, 'Good job', 'dennisanello@kaiyue.com', 'lenasmith@kaiyue.com', ''),
       (4, 'Good job', 'larryangers@kaiyue.com', 'lenasmith@kaiyue.com', ''),
       (4, 'Good job', 'johnangle@kaiyue.com', 'tomtaylor@kaiyue.com', ''),
       (4, 'Good job', 'richardannear@kaiyue.com','tomtaylor@kaiyue.com', ''),
       (4, 'Good job', 'danielano@kaiyue.com', 'tomtaylor@kaiyue.com', ''),
       (4, 'Good job', 'robertansell@kaiyue.com', 'nicolgreen@kaiyue.com', ''),
       (4, 'Good job', 'betsyanswer@kaiyue.com', 'nicolgreen@kaiyue.com', ''),
       (4, 'Good job', 'scottantin@kaiyue.com', 'paulmiller@kaiyue.com', ''),
       (4, 'Good job', 'jamesbaheti@kaiyue.com', 'paulmiller@kaiyue.com', ''),
       (4, 'Good job', 'ellenbak@kaiyue.com', 'paulmiller@kaiyue.com', ''),
       (4, 'Good job', 'robertbarchi@kaiyue.com', 'alenlee@kaiyue.com', ''),
       (4, 'Good job', 'shirleybard@kaiyue.com', 'alenlee@kaiyue.com', ''),
       (4, 'Good job', 'johnbarlow@kaiyue.com', 'davidking@kaiyue.com', ''),
       (4, 'Good job', 'carolbarnes@kaiyue.com', 'davidking@kaiyue.com', ''),
       (4, 'Good job', 'harrytruman@kaiyue.com', 'davidking@kaiyue.com', ''),
       (4, 'Good job', 'franklindelano@kaiyue.com', 'obmarking@kaiyue.com', ''),
       (4, 'Good job', 'johnkennedy@kaiyue.com', 'obmarking@kaiyue.com', ''),
       (4, 'Good job', 'richardnixon@kaiyue.com', 'jonesmith@kaiyue.com', ''),
       (4, 'Good job', 'geraldford@kaiyue.com', 'jonesmith@kaiyue.com', ''),
       (4, 'Good job', 'jimmycarter@kaiyue.com', 'jonesmith@kaiyue.com', ''),
       (4, 'Good job', 'ronaldreagan@kaiyue.com', 'lucywhite@kaiyue.com', ''),
       (4, 'Good job', 'georgbush@kaiyue.com', 'lucywhite@kaiyue.com', ''),
       (4, 'Good job', 'paulgarry@kaiyue.com', 'joannasmith@kaiyue.com', ''),
       (4, 'Good job', 'marywhite@kaiyue.com', 'joannasmith@kaiyue.com', ''),
       (4, 'Good job', 'dawncarter@kaiyue.com', 'joannasmith@kaiyue.com', ''),
       (4, 'Good job', 'annaharbor@gmail.com', 'johndoe@sean.com', ''),
       (4, 'Good job', 'goldyfish@gmail.com', 'johndoe@sean.com', ''),
       (4, 'Good job', 'greengoblin@gmail.com', 'johndoe@sean.com', ''),
       (5, 'Good job', 'jackhumpty@gmail.com','johndoe@sean.com', ''),
       (4, 'Good job', 'shinchan@gmail.com', 'bobpancakes@sean.com', ''),
       (4, 'Good job', 'alimiyaan@gmail.com', 'judidench@sean.com', ''),
       (4, 'Good job', 'ramkapoor@gmail.com', 'judidench@sean.com', ''),
       (4, 'Good job', 'andygoshun@gmail.com', 'judidench@sean.com', ''),
       (2, 'Bad job', 'leokaplin@gmail.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'coryanderson@gmail.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'clarkekent@gmail.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'brucewayne@gmail.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'walterwhistle@gmail.com', 'marktwain@sean.com', ''),
       (4, 'Good job', 'shinyuu@gmail.com', 'marktwain@sean.com', ''),
       (3, 'Average job', 'oliviaredson@gmail.com', 'billsomeone@sean.com', ''),
       (4, 'Good job', 'hilarybirgham@gmail.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'shirleygordon@gmail.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'pinkydsuza@gmail.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'garyshimmer@gmail.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'amywinehouse@gmail.com', 'queenelizabeth@sean.com', ''),
       (5, 'Excellent job', 'donmaroni@gmail.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'alisonfinn@gmail.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'jonahhill@gmail.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'samsmith@gmail.com', 'austinpowers@sean.com', ''),
       (4, 'Good job', 'jonesBlack@gmail.com', 'austinpowers@sean.com', ''),
       (4, 'Excellent!', 'Rebecca@gmail.com', 'Amera@yahoo.com', ''),
       (5, 'Good job', 'Sara_George@gmail.com', 'Amera@yahoo.com', ''),
       (4, 'Excellent!', 'Aaron@outlook.com', 'Amera@yahoo.com', ''),
       (4, 'Good job', 'Ayman15@gmail.com','Amera@yahoo.com', ''),
       (4, 'Good job', 'Javed@gmail.com', 'Amera@yahoo.com', ''),
       (4, 'Good job', 'Rebecca@gmail.com', 'Michael@gmail.com', ''),
       (5, 'Good job', 'Sara_George@gmail.com', 'Michael@gmail.com', ''),
       (4, 'Excellent!', 'Aaron@outlook.com', 'Michael@gmail.com', ''),
       (4, 'Good job', 'Ayman15@gmail.com', 'Michael@gmail.com', ''),
       (4, 'Good job', 'Javed@gmail.com', 'Michael@gmail.com', ''),
       (4, 'Good job', 'Rebecca@gmail.com', 'Yasser@yahoo.com', ''),
       (5, 'Good job', 'Sara_George@gmail.com', 'Yasser@yahoo.com', ''),
       (4, 'Good job', 'Aaron@outlook.com', 'Yasser@yahoo.com', ''),
       (4, 'Excellent!', 'Ayman15@gmail.com', 'Yasser@yahoo.com', ''),
       (4, 'Good job', 'Javed@gmail.com', 'Yasser@yahoo.com', ''),
       (4, 'Good job', 'Rebecca@gmail.com', 'Yasmin@outlook.com', ''),
       (4, 'Good job', 'Sara_George@gmail.com', 'Yasmin@outlook.com', ''),
       (4, 'Excellent!', 'Aaron@outlook.com', 'Yasmin@outlook.com', ''),
       (5, 'Good job', 'Ayman15@gmail.com', 'Yasmin@outlook.com', ''),
       (4, 'Good job', 'Javed@gmail.com', 'Yasmin@outlook.com', ''),
       (4, 'Good job', 'Rebecca@gmail.com', 'Turkey@gmail.com', ''),
       (4, 'Good job', 'Sara_George@gmail.com', 'Turkey@gmail.com', ''),
       (4, 'Excellent!', 'Aaron@outlook.com', 'Turkey@gmail.com', ''),
       (5, 'Good job', 'Ayman15@gmail.com', 'Turkey@gmail.com', ''),
       (4, 'Good job', 'Javed@gmail.com', 'Turkey@gmail.com', '');
