INSERT INTO `website_user` (`name`, `username`, `password`, `type`) VALUES
       ('John Doe', 'johndoe@sean.com', 'pass', 'patient'),
       ('Jane Doe', 'janedoe@sean.com', 'pass', 'patient'),
       ('Bob Panckes', 'bobpancakes@sean.com', 'pass', 'patient'),
       ('Betty McBoss', 'bettymcboss@sean.com', 'pass', 'patient'),
       ('Bill Someone', 'billsomeone@sean.com', 'pass', 'patient'),
       ('Whatshisface', 'whatshisface@sean.com', 'pass', 'patient'),
       ('Austin Powers', 'austinpowers@sean.com', 'pass', 'patient'),
       ('Queen Elizabeth II', 'queenelizabeth@sean.com', 'pass', 'patient'),
       ('Judi Dench', 'judidench@sean.com', 'pass', 'patient'),
       ('Mark Twain', 'marktwain@sean.com', 'pass', 'patient'),
       ('Johnny Shen','johnnyshen@sean.com', 'pass', 'doctor'),
       ('Igor Borisov', 'igorborisov@sean.com', 'pass', 'doctor'),
       ('Carolynn Brown', 'carolynnbrown@sean.com', 'pass', 'doctor'),
       ('Nazia Javed', 'naziajaved@sean.com', 'pass', 'doctor'),
       ('Daniel Witten', 'danielwitten@sean.com', 'pass', 'doctor'),
       ('Theodore Buttrick', 'theodorebuttrick@sean.com', 'pass', 'doctor'),
       ('Danielle Hawkins', 'daniellehawkins@sean.com', 'pass', 'doctor'),
       ('Samantha Ghiselli', 'samanthaghiselli@sean.com', 'pass', 'doctor'),
       ('Carrie Hill', 'carriehill@sean.com', 'pass', 'doctor'),
       ('Nancy Krywonis', 'nancykrywonis@sean.com', 'pass', 'doctor'),
       ('Marti Freidnash', 'martifreidnash@sean.com', 'pass', 'doctor'),
       ('Robert Packer', 'robertpacker@sean.com', 'pass', 'doctor'),
       ('Harrison Levine', 'harrisonlevine@sean.com', 'pass', 'doctor'),
       ('Beth Ballen', 'bethballen@sean.com', 'pass', 'doctor'),
       ('Robinette Ball', 'robinetteball@sean.com', 'pass', 'doctor'),
       ('Joel Cooperman', 'joelcooperman@sean.com', 'pass', 'doctor'),
       ('Stuart Myers', 'stuartmyers@sean.com', 'pass', 'doctor'),
       ('Michael Hewitt', 'michaelhewitt@sean.com', 'pass', 'doctor'),
       ('Rudy Kovachevich', 'rudykovachevich@sean.com', 'pass', 'doctor'),
       ('Scott Resig', 'scottresig@sean.com', 'pass', 'doctor'),
       ('Mark Failinger', 'markfailinger@sean.com', 'pass', 'doctor'),
       ('Joanne Takara', 'joannetakara@sean.com', 'pass', 'doctor'),
       ('James Burcham', 'jamesburcham@sean.com', 'pass', 'doctor'),
       ('Matthew Kruger', 'matthewkruger@sean.com', 'pass', 'doctor'),
       ('Robert Keyser', 'robertkeyser@sean.com', 'pass', 'doctor'),
       ('Admin 1', 'superadmin1@gmail.com', 'pass', 'admin'),
       ('Admin 2', 'superadmin2@gmail.com', 'pass', 'admin'),
       ('Admin 3', 'superadmin3@gmail.com', 'pass', 'admin'),
       ('Admin 4', 'superadmin4@gmail.com', 'pass', 'admin'),
       ('Admin 5', 'superadmin5@gmail.com', 'pass', 'admin'),
       ('Lena Smith', 'lenasmith@kaiyue.com', 'pass', 'patient'),
       ('Tom Taylor', 'tomtaylor@kaiyue.com', 'pass', 'patient'),
       ('Nicol Green', 'nicolgreen@kaiyue.com', 'pass', 'patient'),
       ('Paul Miller', 'paulmiller@kaiyue.com', 'pass', 'patient'),
       ('Alen Lee', 'alenlee@kaiyue.com', 'pass', 'patient'),
       ('David King', 'davidking@kaiyue.com', 'pass', 'patient'),
       ('Obmar King', 'obmarking@kaiyue.com', 'pass', 'patient'),
       ('Jone Smith', 'jonesmith@kaiyue.com', 'pass', 'patient'),
       ('Lucy White', 'lucywhite@kaiyue.com', 'pass', 'patient'),
       ('Joanna Smith', 'joannasmith@kaiyue.com', 'pass', 'patient'),
       ('Dennis Anello','dennisanello@kaiyue.com', 'pass', 'doctor'),
       ('Larry Angers', 'larryangers@kaiyue.com', 'pass', 'doctor'),
       ('John Angle', 'johnangle@kaiyue.com', 'pass', 'doctor'),
       ('Richard Annear', 'richardannear@kaiyue.com', 'pass', 'doctor'),
       ('Daniel Ano', 'danielano@kaiyue.com', 'pass', 'doctor'),
       ('Robert Ansell', 'robertansell@kaiyue.com', 'pass', 'doctor'),
       ('Betsy Answer', 'betsyanswer@kaiyue.com', 'pass', 'doctor'),
       ('Scott Antin', 'scottantin@kaiyue.com', 'pass', 'doctor'),
       ('James Baheti', 'jamesbaheti@kaiyue.com', 'pass', 'doctor'),
       ('Ellen Bak', 'ellenbak@kaiyue.com', 'pass', 'doctor'),
       ('Robert Barchi', 'robertbarchi@kaiyue.com', 'pass', 'doctor'),
       ('Shirley Bard', 'shirleybard@kaiyue.com', 'pass', 'doctor'),
       ('John Barlow', 'johnbarlow@kaiyue.com', 'pass', 'doctor'),
       ('Carol Barnes', 'carolbarnes@kaiyue.com', 'pass', 'doctor'),
       ('Harry Truman', 'harrytruman@kaiyue.com', 'pass', 'doctor'),
       ('Franklin Delano', 'franklindelano@kaiyue.com', 'pass', 'doctor'),
       ('John Kennedy', 'johnkennedy@kaiyue.com', 'pass', 'doctor'),
       ('Richard Nixon', 'richardnixon@kaiyue.com', 'pass', 'doctor'),
       ('Gerald Ford', 'geraldford@kaiyue.com', 'pass', 'doctor'),
       ('Jimmy Carter', 'jimmycarter@kaiyue.com', 'pass', 'doctor'),
       ('Ronald Reagan', 'ronaldreagan@kaiyue.com', 'pass', 'doctor'),
       ('George Bush', 'georgbush@kaiyue.com', 'pass', 'doctor'),
       ('Paul Garry', 'paulgarry@kaiyue.com', 'pass', 'doctor'),
       ('Mary White', 'marywhite@kaiyue.com', 'pass', 'doctor'),
       ('Dawn Carter', 'dawncarter@kaiyue.com', 'pass', 'doctor'),
       ('Admin 6', 'superadmin6@kaiyue.com', 'pass', 'admin'),
       ('Admin 7', 'superadmin7@kaiyue.com', 'pass', 'admin'),
       ('Admin 8', 'superadmin8@kaiyue.com', 'pass', 'admin'),
       ('Admin 9', 'superadmin9@kaiyue.com', 'pass', 'admin'),
       ('Admin 10', 'superadmin10@kaiyue.com', 'pass', 'admin');

INSERT INTO `website_doctor` (`phoneNumber`, `officeHours`, `speciality`, `rating`, `availability`, `state`, `city`, `zip`, `street`, `education`, `awards`, `experience`, `username_id`) VALUES
       ('3036928000', 'Mon-Fri: 8 - 5', 'Primary Care', 5, '', 'Colorado', 'Denver', '80246', '760 South Colorado Blvd.', 'University of Texas, San Antonio', '', 'Dr. Shen is a board-certified physician with a specialty in family medicine', 'johnnyshen@sean.com'),
       ('', 'Mon-Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80220', '4500 East 9th Avenue', 'Vilnius Univeristy of Medicine', '', 'Good Samaritan Hospital Residence in Internal Medicine', 'igorborisov@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80220', '50 South Steele Street', 'University of Colorado', '', 'Rose Medical Center Residency in Family Medicine', 'carolynnbrown@sean.com'),
       ('', 'Mon - Fri: 8 -5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80239', '10515 East 40th Ave.', 'King Edward Medical University', '', 'Pheonix Baptist Hospital, Residency in Family Medicine', 'naziajaved@sean.com'),
       ('', 'Mon - Fri: 8-5', 'Primary Care', 5, '', 'Colorado', 'Denver', '80220', '4500 East 9th Avenue', 'Vilnius University of Medicine', '', 'University of Colorado Residency in Internal Medicine', 'danielwitten@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Primary Care', 5, '', 'Colorado', 'Wheatridge', '80033', '4045 Wadsworth Blvd.', 'Wayne State Univeristy', '', 'Saint Luke Medical Center Residency', 'theodorebuttrick@sean.com'),
       ('', 'Mon-Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80207', '2970 Quebec Street', 'Michigan State University', '', 'University of New Mexico, Residency in Dermatology', 'daniellehawkins@sean.com'),
       ('', 'Mon-Fri: 8 - 5', 'Dermatologist', 4.5, '', 'Colorado', 'Denver', '80207', '2970 Quebec Street', 'University of California Irvine', '', 'University of California Irvine, residency in Dermatology', 'samanthaghiselli@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Dermatologist', 4.5, '', 'Colroado', 'Denver', '80206', '3300 East 1st Ave', 'University of Colorado', '', 'University of Iowa, Residency in Dermatology', 'carriehill@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80220', '4545 E 9th Ave', 'University of Manitoba Faculty of Medicine', '', 'University of Minnesota, Residency in Dermatology', 'nancykrywonis@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80230', '130 Rampart Way', 'University of Colorado', '', 'University of Colorado Hospital, Residency in Dermatology', 'martifreidnash@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Wheatridge', '80033', '8550 W. 38th Avenue', 'University of Tennesse', '', 'Vanderbilt University Medical Center, Residency in Dermatology', 'robertpacker@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80206', '3570 E 12th Ave', 'Columbia University, Medical School for International Health', '', 'University of Michigan, Residency', 'harrisonlevine@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Centennial', '80111', '6081 S Quebec St', 'Eastern Virginia Medical School', '', 'University of Colorado, Residency in General Psychiatry', 'bethballen@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80246', '4550 E Cherry Creek South Drive', 'Columbia University', '', 'Bronx University, Internship', 'robinetteball@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80014', '10555 E Dartmouth Ave', 'A.T. Stills University, Kirksville', '', 'rand View Hospital, Residency in Orthopedic Surgery', 'joelcooperman@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1411 South Potomac Street', 'University of Pennsylvania', '', 'ohn Hopkins University, Residency in Orthopedic Surgery', 'stuartmyers@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1411 South Potomac Street', 'Tufts University', '', 'Harbor-University California Los Angeles, Residency', 'michaelhewitt@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1300 South Potomac Street', 'University of Illinois, Chicago', '', 'Mayo Clinic, Residency in Orthopedic Surgery', 'rudykovachevich@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '8101 E. Lowry Blvd', 'University of Minnesota', '', 'University of Minnesota, Residency in Orthopedic Surgery', 'scottresig@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '8101 E Lowry Blvd', 'University of Minnesota, Twin Cities', '', 'University of Texas, Residency in Orthopedic Surgery', 'markfailinger@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Aurora', '80011', '750 Potomac Street', 'Indiana University', '', 'Tucson Veterans Affairs Medical Center, Residency', 'joannetakara@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Aurora', '80011', '750 Potomac Street', 'University of Missouri, Columbia', '', 'University of Colorado, Residency in Opthalmology', 'jamesburcham@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Denver', '80246', '4999 E Kentucky Ave', 'Tufts University', '', 'University of Texas, Southwestern, Residency in Opthalmology', 'matthewkruger@sean.com'),
       ('', 'Mon - Fri: 8 - 5', 'Eye Doctor', 4.5, '', 'Colorado', 'Lakewood', '80228', '11750 W 2nd Place', 'University of Michigan', '', 'University of Colorado, Residency in Opthalmology', 'robertkeyser@sean.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Primary Care', 5, '', 'Colorado', 'Denver', '80246', '760 South Colorado Blvd.', 'University of Texas, San Antonio', '', 'Dr. Shen is a board-certified physician with a specialty in family medicine', 'dennisanello@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80220', '4500 East 9th Avenue', 'Vilnius Univeristy of Medicine', '', 'Good Samaritan Hospital Residence in Internal Medicine', 'larryangers@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80220', '50 South Steele Street', 'University of Colorado', '', 'Rose Medical Center Residency in Family Medicine', 'johnangle@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Primary Care', 4, '', 'Colorado', 'Denver', '80239', '10515 East 40th Ave.', 'King Edward Medical University', '', 'Pheonix Baptist Hospital, Residency in Family Medicine', 'richardannear@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80220', '4500 East 9th Avenue', 'Vilnius University of Medicine', '', 'University of Colorado Residency in Internal Medicine', 'danielano@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Wheatridge', '80033', '4045 Wadsworth Blvd.', 'Wayne State Univeristy', '', 'Saint Luke Medical Center Residency', 'robertansell@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80207', '2970 Quebec Street', 'Michigan State University', '', 'University of New Mexico, Residency in Dermatology', 'betsyanswer@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 4.5, '', 'Colorado', 'Denver', '80207', '2970 Quebec Street', 'University of California Irvine', '', 'University of California Irvine, residency in Dermatology', 'scottantin@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Dermatologist', 4.5, '', 'Colroado', 'Denver', '80206', '3300 East 1st Ave', 'University of Colorado', '', 'University of Iowa, Residency in Dermatology', 'jamesbaheti@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80220', '4545 E 9th Ave', 'University of Manitoba Faculty of Medicine', '', 'University of Minnesota, Residency in Dermatology', 'ellenbak@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Denver', '80230', '130 Rampart Way', 'University of Colorado', '', 'University of Colorado Hospital, Residency in Dermatology', 'robertbarchi@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Dermatologist', 5, '', 'Colorado', 'Wheatridge', '80033', '8550 W. 38th Avenue', 'University of Tennesse', '', 'Vanderbilt University Medical Center, Residency in Dermatology', 'shirleybard@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80206', '3570 E 12th Ave', 'Columbia University, Medical School for International Health', '', 'University of Michigan, Residency', 'johnbarlow@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Centennial', '80111', '6081 S Quebec St', 'Eastern Virginia Medical School', '', 'University of Colorado, Residency in General Psychiatry', 'carolbarnes@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Psychiatrist', 5, '', 'Colorado', 'Denver', '80246', '4550 E Cherry Creek South Drive', 'Columbia University', '', 'Bronx University, Internship', 'harrytruman@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80014', '10555 E Dartmouth Ave', 'A.T. Stills University, Kirksville', '', 'rand View Hospital, Residency in Orthopedic Surgery', 'franklindelano@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1411 South Potomac Street', 'University of Pennsylvania', '', 'ohn Hopkins University, Residency in Orthopedic Surgery', 'johnkennedy@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1411 South Potomac Street', 'Tufts University', '', 'Harbor-University California Los Angeles, Residency', 'richardnixon@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 5, '', 'Colorado', 'Aurora', '80012', '1300 South Potomac Street', 'University of Illinois, Chicago', '', 'Mayo Clinic, Residency in Orthopedic Surgery', 'geraldford@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '8101 E. Lowry Blvd', 'University of Minnesota', '', 'University of Minnesota, Residency in Orthopedic Surgery', 'jimmycarter@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Orthopedist', 4.5, '', 'Colorado', 'Denver', '80230', '8101 E Lowry Blvd', 'University of Minnesota, Twin Cities', '', 'University of Texas, Residency in Orthopedic Surgery', 'ronaldreagan@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Aurora', '80011', '750 Potomac Street', 'Indiana University', '', 'Tucson Veterans Affairs Medical Center, Residency', 'georgbush@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Aurora', '80011', '750 Potomac Street', 'University of Missouri, Columbia', '', 'University of Colorado, Residency in Opthalmology', 'paulgarry@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Eye Doctor', 5, '', 'Colorado', 'Denver', '80246', '4999 E Kentucky Ave', 'Tufts University', '', 'University of Texas, Southwestern, Residency in Opthalmology', 'marywhite@kaiyue.com'),
       ('3036928000', 'Mon - Fri: 8 - 5', 'Eye Doctor', 4.5, '', 'Colorado', 'Lakewood', '80228', '11750 W 2nd Place', 'University of Michigan', '', 'University of Colorado, Residency in Opthalmology', 'dawncarter@kaiyue.com');

INSERT INTO `website_favoritedoctors` (`patient_id`, `doctor_id`) VALUES
       ('marktwain@sean.com', 'johnnyshen@sean.com'),
       ('marktwain@sean.com', 'michaelhewitt@sean.com'),
       ('bobpancakes@sean.com', 'igorborisov@sean.com'),
       ('bettymcboss@sean.com', 'rudykovachevich@sean.com'),
       ('bettymcboss@sean.com', 'joannetakara@sean.com'),
       ('bettymcboss@sean.com', 'stuartmyers@sean.com'),
       ('bettymcboss@sean.com', 'theodorebuttrick@sean.com'),
       ('bettymcboss@sean.com', 'bethballen@sean.com'),
       ('bettymcboss@sean.com', 'danielwitten@sean.com'),
       ('bettymcboss@sean.com', 'carriehill@sean.com'),
       ('bettymcboss@sean.com', 'robertkeyser@sean.com'),
       ('billsomeone@sean.com', 'robertkeyser@sean.com'),
       ('billsomeone@sean.com', 'theodorebuttrick@sean.com'),
       ('johndoe@sean.com', 'bethballen@sean.com'),
       ('johndoe@sean.com', 'theodorebuttrick@sean.com'),
       ('johndoe@sean.com', 'markfailinger@sean.com'),
       ('johndoe@sean.com', 'harrisonlevine@sean.com'),
       ('johndoe@sean.com', 'jamesburcham@sean.com'),
       ('judidench@sean.com', 'johnnyshen@sean.com'),
       ('judidench@sean.com', 'theodorebuttrick@sean.com'),
       ('judidench@sean.com', 'igorborisov@sean.com'),
       ('judidench@sean.com', 'nancykrywonis@sean.com'),
       ('janedoe@sean.com', 'naziajaved@sean.com'),
       ('janedoe@sean.com', 'joelcooperman@sean.com'),
       ('janedoe@sean.com', 'igorborisov@sean.com'),
       ('lenasmith@kaiyue.com', 'dennisanello@kaiyue.com'),
       ('lenasmith@kaiyue.com', 'larryangers@kaiyue.com'),   
       ('tomtaylor@kaiyue.com', 'johnangle@kaiyue.com'),
       ('tomtaylor@kaiyue.com', 'richardannear@kaiyue.com'),
       ('tomtaylor@kaiyue.com', 'danielano@kaiyue.com'),   
       ('nicolgreen@kaiyue.com', 'robertansell@kaiyue.com'),
       ('nicolgreen@kaiyue.com', 'betsyanswer@kaiyue.com'),    
       ('paulmiller@kaiyue.com', 'scottantin@kaiyue.com'),
       ('paulmiller@kaiyue.com', 'jamesbaheti@kaiyue.com'),
       ('paulmiller@kaiyue.com', 'ellenbak@kaiyue.com'),
       ('alenlee@kaiyue.com', 'robertbarchi@kaiyue.com'),
       ('alenlee@kaiyue.com', 'shirleybard@kaiyue.com'),
       ('davidking@kaiyue.com', 'johnbarlow@kaiyue.com'),
       ('davidking@kaiyue.com', 'carolbarnes@kaiyue.com'),
       ('davidking@kaiyue.com', 'harrytruman@kaiyue.com'),   
       ('obmarking@kaiyue.com', 'franklindelano@kaiyue.com'),
       ('obmarking@kaiyue.com', 'johnkennedy@kaiyue.com'),   
       ('jonesmith@kaiyue.com', 'richardnixon@kaiyue.com'),
       ('jonesmith@kaiyue.com', 'geraldford@kaiyue.com'),
       ('jonesmith@kaiyue.com', 'jimmycarter@kaiyue.com'),
       ('lucywhite@kaiyue.com', 'ronaldreagan@kaiyue.com'),
       ('lucywhite@kaiyue.com', 'georgbush@kaiyue.com'),
       ('joannasmith@kaiyue.com', 'paulgarry@kaiyue.com'),
       ('joannasmith@kaiyue.com', 'marywhite@kaiyue.com'),
       ('joannasmith@kaiyue.com', 'dawncarter@kaiyue.com');

INSERT INTO `website_insurance` (`name`, `doctor_id`) VALUES
       ('Aetna', 'johnnyshen@sean.com'),
       ('Cigna', 'johnnyshen@sean.com'),
       ('Medicare', 'johnnyshen@sean.com'),
       ('United', 'johnnyshen@sean.com'),
       ('Aetna', 'igorborisov@sean.com'),
       ('Blue', 'igorborisov@sean.com'),
       ('Cigna', 'igorborisov@sean.com'),
       ('United', 'igorborisov@sean.com'),
       ('Aetna', 'carolynnbrown@sean.com'),
       ('Blue', 'carolynnbrown@sean.com'),
       ('Cigna', 'carolynnbrown@sean.com'),
       ('United', 'carolynnbrown@sean.com'),
       ('Aetna', 'naziajaved@sean.com'),
       ('Blue', 'naziajaved@sean.com'),
       ('Cigna', 'naziajaved@sean.com'),
       ('United', 'naziajaved@sean.com'),
       ('Aetna', 'danielwitten@sean.com'),
       ('Blue', 'danielwitten@sean.com'),
       ('Cigna', 'danielwitten@sean.com'),
       ('United', 'danielwitten@sean.com'),
       ('Aetna', 'theodorebuttrick@sean.com'),
       ('Blue', 'theodorebuttrick@sean.com'),
       ('Cigna', 'theodorebuttrick@sean.com'),
       ('Medicare', 'theodorebuttrick@sean.com'),
       ('United', 'theodorebuttrick@sean.com'),
       ('Aetna', 'dennisanello@kaiyue.com'),
       ('Cigna', 'dennisanello@kaiyue.com'),
       ('Medicare', 'dennisanello@kaiyue.com'),
       ('United', 'dennisanello@kaiyue.com'),
       ('Aetna', 'larryangers@kaiyue.com'),
       ('Blue', 'larryangers@kaiyue.com'),
       ('Cigna', 'larryangers@kaiyue.com'),
       ('United', 'larryangers@kaiyue.com'),
       ('Aetna', 'johnangle@kaiyue.com'),
       ('Blue', 'johnangle@kaiyue.com'),
       ('Cigna', 'johnangle@kaiyue.com'),
       ('United', 'johnangle@kaiyue.com'),
       ('Aetna', 'richardannear@kaiyue.com'),
       ('Blue', 'richardannear@kaiyue.com'),
       ('Cigna', 'richardannear@kaiyue.com'),
       ('United', 'richardannear@kaiyue.com'),
       ('Aetna', 'danielano@kaiyue.com'),
       ('Blue', 'danielano@kaiyue.com'),
       ('Cigna', 'danielano@kaiyue.com'),
       ('United', 'danielano@kaiyue.com'),
       ('Aetna', 'robertansell@kaiyue.com'),
       ('Blue', 'robertansell@kaiyue.com'),
       ('Cigna', 'robertansell@kaiyue.com'),
       ('Medicare', 'robertansell@kaiyue.com'),
       ('United', 'robertansell@kaiyue.com');

INSERT INTO `website_review` (`rating`, `comment`, `doctor_id`, `patient_id`, `date`) VALUES
       (4, 'Good job', 'johnnyshen@sean.com', 'johndoe@sean.com', ''),
       (4, 'Good job', 'theodorebuttrick@sean.com', 'johndoe@sean.com', ''),
       (4, 'Good job', 'igorborisov@sean.com', 'johndoe@sean.com', ''),
       (4, 'Good job', 'markfailinger@sean.com','johndoe@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'bobpancakes@sean.com', ''),
       (4, 'Good job', 'carriehill@sean.com', 'judidench@sean.com', ''),
       (4, 'Good job', 'theodorebuttrick@sean.com', 'judidench@sean.com', ''),
       (4, 'Good job', 'matthewkruger@sean.com', 'judidench@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'theodorebuttrick@sean.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'danielwitten@sean.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'joannetakara@sean.com', 'bettymcboss@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'marktwain@sean.com', ''),
       (4, 'Good job', 'robertkeyser@sean.com', 'marktwain@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'billsomeone@sean.com', ''),
       (4, 'Good job', 'naziajaved@sean.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'robertkeyser@sean.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'rudykovachevich@sean.com', 'janedoe@sean.com', ''),
       (4, 'Good job', 'johnnyshen@sean.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'harrisonlevine@sean.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'bethballen@sean.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'carolynnbrown@sean.com', 'queenelizabeth@sean.com', ''),
       (4, 'Good job', 'stuartmyers@sean.com', 'austinpowers@sean.com', ''),
       (4, 'Good job', 'robinetteball@sean.com', 'austinpowers@sean.com', ''),
       (4, 'Good job', 'dennisanello@kaiyue.com', 'lenasmith@kaiyue.com', ''),
       (4, 'Good job', 'larryangers@kaiyue.com', 'lenasmith@kaiyue.com', ''),
       (4, 'Good job', 'johnangle@kaiyue.com', 'tomtaylor@kaiyue.com', ''),
       (4, 'Good job', 'richardannear@kaiyue.com','tomtaylor@kaiyue.com', ''),
       (4, 'Good job', 'danielano@kaiyue.com', 'tomtaylor@kaiyue.com', ''),
       (4, 'Good job', 'robertansell@kaiyue.com', 'nicolgreen@kaiyue.com', ''),
       (4, 'Good job', 'betsyanswer@kaiyue.com', 'nicolgreen@kaiyue.com', ''),
       (4, 'Good job', 'scottantin@kaiyue.com', 'paulmiller@kaiyue.com', ''),
       (4, 'Good job', 'jamesbaheti@kaiyue.com', 'paulmiller@kaiyue.com', ''),
       (4, 'Good job', 'ellenbak@kaiyue.com', 'paulmiller@kaiyue.com', ''),
       (4, 'Good job', 'robertbarchi@kaiyue.com', 'alenlee@kaiyue.com', ''),
       (4, 'Good job', 'shirleybard@kaiyue.com', 'alenlee@kaiyue.com', ''),
       (4, 'Good job', 'johnbarlow@kaiyue.com', 'davidking@kaiyue.com', ''),
       (4, 'Good job', 'carolbarnes@kaiyue.com', 'davidking@kaiyue.com', ''),
       (4, 'Good job', 'harrytruman@kaiyue.com', 'davidking@kaiyue.com', ''),
       (4, 'Good job', 'franklindelano@kaiyue.com', 'obmarking@kaiyue.com', ''),
       (4, 'Good job', 'johnkennedy@kaiyue.com', 'obmarking@kaiyue.com', ''),
       (4, 'Good job', 'richardnixon@kaiyue.com', 'jonesmith@kaiyue.com', ''),
       (4, 'Good job', 'geraldford@kaiyue.com', 'jonesmith@kaiyue.com', ''),
       (4, 'Good job', 'jimmycarter@kaiyue.com', 'jonesmith@kaiyue.com', ''),
       (4, 'Good job', 'ronaldreagan@kaiyue.com', 'lucywhite@kaiyue.com', ''),
       (4, 'Good job', 'georgbush@kaiyue.com', 'lucywhite@kaiyue.com', ''),
       (4, 'Good job', 'paulgarry@kaiyue.com', 'joannasmith@kaiyue.com', ''),
       (4, 'Good job', 'marywhite@kaiyue.com', 'joannasmith@kaiyue.com', ''),
       (4, 'Good job', 'dawncarter@kaiyue.com', 'joannasmith@kaiyue.com', '');
